#!/bin/sh
docker container rm wine-gta2-1
docker container rm wine-gta2-2
docker container rm wine-gta2-3
docker container rm wine-gta2-4
docker container rm wine-gta2-5
docker container rm wine-gta2-6

